export const ADD_TO_BASKET = "ADD_TO_BASKET"
export const REOMVE_FROM_BASKET = "REOMVE_FROM_BASKET"
export const INCREASE_ITEM_QUANTITY = "INCREASE_ITEM_QUANTITY"
export const FROM_STORAGE_TO_BASKET = "FROM_STORAGE_TO_BASKET"